# Synonyms of either "risk" or "uncertainty" to be used in text analysis. The words
#   "Question" and "Questions" are omitted since they are too common in Q&A sections and
#   would likely introduce false positives
RISK_SYNONYMS = [
    "uncertainty",
    "uncertainties",
    "risk",
    "uncertain",
    "risks",
    "unknown",
    "possibility",
    "pending",
    "exposed",
    "threat",
    "instability",
    "fear",
    "doubt",
    "unclear",
    "unresolved",
    "chance",
    "likelihood",
    "probability",
    "unpredictable",
    "unsettled",
    "Word",
    "variable",
    "prospect",
    "unpredictability",
    "insecurity",
    "danger",
    "faltering",
    "unstable",
    "unsure",
    "risky",
    "bet",
    "suspicion",
    "indecision",
    "hesitant",
    "hesitating",
    "dilemma",
    "indecisive",
    "apprehension",
    "ﬂuctuating",
    "speculative",
    "sticky",
]
